name: github_sign_in
description: Sign In With GitHub
version: 0.0.6
homepage: https://github.com/jayfinava-benzatine/GITHUB_SIGN_IN

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
